### PR TITLE
Feature/bayes r

### PR DESCRIPTION
**Pull request by mammykins**
Intro to A / B testing and a bit of a refresher on Frequentist statistics.

### CODE REVIEW

**Review by ivyleavedtoadflax — COMMENTED** [review]
I'd be inclined to squash these commits into one - it's quite a lot for a single post.

**Review by ivyleavedtoadflax — COMMENTED** [review]
Looks good @mammykins - you will need to merge now that I have added commits

**Comment by mammykins** [comment]
Merged your changes @ivyleavedtoadflax

**Review by ivyleavedtoadflax — APPROVED** [review]
This looks all good to merge now @mammykins

**Pull request merged**
